In [62]:
import numpy as np
import tensorflow as tf
from softmax import softmax, softmax_cross_entropy_with_logits
from scipy.special import expit

In [63]:
X = np.array([[-1.0, 2], [-1, 3], [3, 4]])
Y = np.array([[0, 1], [1, 0], [0, 1]])

In [64]:
print softmax(X)

with tf.Session() as sess:
    print tf.nn.softmax(X).eval()

[[ 0.04742587  0.95257413]
 [ 0.01798621  0.98201379]
 [ 0.26894142  0.73105858]]
[[ 0.04742587  0.95257413]
 [ 0.01798621  0.98201379]
 [ 0.26894142  0.73105858]]


In [65]:
print expit(X)

with tf.Session() as sess:
    print tf.nn.sigmoid(X).eval()

[[ 0.26894142  0.88079708]
 [ 0.26894142  0.95257413]
 [ 0.95257413  0.98201379]]
[[ 0.26894142  0.88079708]
 [ 0.26894142  0.95257413]
 [ 0.95257413  0.98201379]]


In [66]:
print softmax_cross_entropy_with_logits(X, Y)

with tf.Session() as sess:
    print tf.nn.softmax_cross_entropy_with_logits(X, Y).eval()

[-0.04858735 -4.01814993 -0.31326169]
[ 0.04858735  4.01814993  0.31326169]


In [68]:
print np.maximum(X, 0, X)

with tf.Session() as sess:
    print tf.nn.relu(X).eval()

[[ 0.  2.]
 [ 0.  3.]
 [ 3.  4.]]
[[ 0.  2.]
 [ 0.  3.]
 [ 3.  4.]]
