In [2]:
import numpy as np
import htwt

In [3]:
X, y = htwt.get()

In [5]:
def cov(X):
    mean = np.mean(X, axis = 0).reshape(-1, 1)
    return X.T.dot(X) / (len(X) * 1.0) - mean.dot(mean.T)

cov(X)

array([[   19.78331066,   104.01931973],
       [  104.01931973,  1063.86340136]])

In [10]:
def cov(X):
    N, D = X.shape
    mean = np.mean(X, axis = 0).reshape(-1, 1)
    Sigma = np.zeros((D, D))
    
    for x in X:
        a = x.reshape(-1, 1) - mean
        Sigma += np.outer(a, a)
        
    return Sigma / (N * 1.0)

cov(X)

array([[   19.78331066,   104.01931973],
       [  104.01931973,  1063.86340136]])

In [4]:
np.cov(X, rowvar = False, ddof = 0)

array([[   19.78331066,   104.01931973],
       [  104.01931973,  1063.86340136]])