In [17]:
import numpy as np
from scipy.misc import derivative
import sympy as sm
import tensorflow as tf
from tensorflow.python.framework.ops import Tensor
import theano
import theano.tensor as T

def partial(fun):
    def eval(x, i):
        v = x[:]
        def wraps(x):
            v[i] = x
            return fun(v)    
        return derivative(wraps, x[i], dx = 1e-6)
    return eval

fun = lambda x: (3 * x[0] + x[1]) ** 2
x = [0.1, 0.3]

print [partial(fun)(x, i) for i in xrange(len(x))]


def partial(fun):
    def eval(x, i):
        return tf.gradients(fun)
    return eval

x = tf.Variable(0, dtype = tf.float32)
y = tf.Variable(0, dtype = tf.float32)
fun = 3 * x + y

g = partial(fun)
with tf.Session() as sess:
    tf.initialize_all_variables()
    print g({x: 0.1, y: 0.3}).eval()

[3.6000000000202537, 1.1999999999512401]


TypeError: eval() takes exactly 2 arguments (1 given)

In [16]:
import derive
reload(derive)
import sympy as sm
import tensorflow as tf

fun = lambda x: (3 * x[0] + x[1]) ** 2
point = [0.1, 0.3]

grad = derive.grad(fun)
print grad(point)
hess = derive.hess(fun)
print hess(point)

x, y = sm.symbols('x, y')
fun = (3 * x + y) ** 2
grad = derive.grad(fun)
print grad(point)
hess = derive.hess(fun)
print hess(point)

import numpy as np
x = tf.Variable(0, dtype = tf.float32)
y = tf.Variable(0, dtype = tf.float32)
fun = 3 * x + y

hess = derive.hess(fun)
with tf.Session() as sess:
    tf.initialize_all_variables()
    print hess({x: 0.1, y: 0.3}).eval()

[ 3.6  1.2]
[17.999948753733008, 5.9999782919817335, 5.9999782919817335, 1.9999418787719492]
[3.5999999999999996, 1.2000000000000002]
[[ 18.  18.]
 [  2.   2.]]
[[ 0.  0.]
 [ 0.  0.]]


In [72]:
import theano
import theano.tensor as T

# http://deeplearning.net/software/theano/tutorial/gradients.html
    
x = T.dvector('x')
y = x ** 2
cost = y.sum()
gy = T.grad(cost, x)
H, updates = theano.scan(
    lambda i, gy, x: T.grad(gy[i], x),
    sequences = T.arange(gy.shape[0]),
    non_sequences = [gy, x]
)
f = theano.function([x], H, updates = updates)
print f([4, 4])

[[ 2.  0.]
 [ 0.  2.]]


In [76]:
import theano
import theano.tensor as T

# http://stackoverflow.com/questions/30500332/how-to-use-theano-gradient-hessian-example-needed

x = T.dvector('x')
y = T.dvector('y')
input = [x, y]
cost = T.sum(x ** 2 + y ** 2)

f = theano.gradient.hessian(cost, wrt = input)
h = theano.function(input, f)

x = [1, 2]
y = [1, 2]
print h(x, y)

[array([[ 2.,  0.],
       [ 0.,  2.]]), array([[ 2.,  0.],
       [ 0.,  2.]])]


In [4]:
import numpy as np
import scipy.optimize as opt
from converge import Converge
from numpy.linalg import inv

def minimize(f, x, g, H, epsilon = 1e-7, maxsteps = 100):
    x = np.array(x).astype(float)
    converge = Converge(f, epsilon, maxsteps)
    
    while not converge.done(x):
        d = -inv(H(x)).dot(g(x))
        x += d * opt.minimize(lambda eta: f(x + eta * d), 1).x
    return x

In [5]:
from scipy import stats
import scipy.optimize as opt
import derive
reload(derive)

pdf = stats.multivariate_normal((23, 7)).pdf
fun = lambda x: -pdf(x)
x = [21, 6]
g = derive.grad(fun)
H = derive.hess(fun)
print minimize(fun, x, g, H) 
print opt.minimize(fun, x).x
print opt.minimize(fun, x, method = 'Newton-CG', jac = g, hess = H).x

[ 23.00000001   7.        ]
[ 23.           6.99999999]
[ 22.99999977   6.99999988]
