In [54]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
from numpy.linalg import inv, svd, eigh
import pandas as pd
from scipy import stats
from sklearn.decomposition import PCA
import iris

In [45]:
X, y = iris.get()

In [53]:
pca = PCA()
pca.fit(X, y)

PCA(copy=True, n_components=None, whiten=False)

In [64]:
X = np.array([[1, 2], [3, 4], [5, 6]])
w, v = eigh(X.T.dot(X))
print w
print v
print np.cov(X)

[  0.26450509  90.73549491]
[[-0.78489445  0.61962948]
 [ 0.61962948  0.78489445]]
[[ 0.5  0.5  0.5]
 [ 0.5  0.5  0.5]
 [ 0.5  0.5  0.5]]


In [48]:
U, s, V = svd(X)

In [42]:
C = 2
X = np.array([[1, 2], [3, 4], [5, 6]])
W = np.eye(C)
N, D = X.shape

E = np.exp(X.dot(W))
S = np.sum(E, axis = 1)
[[E[i, c] / S[i] for c in range(C)] for i in range(N)]

[[0.2689414213699951, 0.7310585786300049],
 [0.2689414213699951, 0.73105857863000479],
 [0.26894142136999516, 0.7310585786300049]]