In [6]:
import numpy as np
import htwt

In [7]:
def summary(X):
    print np.mean(X)
    print np.cov(X, ddof = 0, rowvar = False)

In [8]:
X, y = htwt.get()
summary(X)

106.50952381
[[   19.78331066   104.01931973]
 [  104.01931973  1063.86340136]]


In [9]:
def scale(X):
    mean = np.mean(X, axis = 0)
    cov = np.cov(X, ddof = 0, rowvar = False)
    return (X - mean) / np.sqrt(np.diag(cov))

summary(scale(X))

-4.58892183512e-16
[[ 1.          0.71700402]
 [ 0.71700402  1.        ]]


In [11]:
import sklearn.preprocessing

def scale(X):
    return sklearn.preprocessing.scale(X)

summary(scale(X))

-4.50433341419e-16
[[ 1.          0.71700402]
 [ 0.71700402  1.        ]]
