In [2]:
import numpy as np

In [ ]:
https://gist.github.com/stober/1946926

In [3]:
C = 2
X = np.array([[1, 2], [3, 4], [5, 6]])
W = np.eye(C)
N, D = X.shape

E = np.exp(X.dot(W))
S = np.sum(E, axis = 1)
[[E[i, c] / S[i] for c in range(C)] for i in range(N)]

[[0.2689414213699951, 0.7310585786300049],
 [0.2689414213699951, 0.73105857863000479],
 [0.26894142136999516, 0.7310585786300049]]

In [4]:
def softmax(w, t = 1.0):
    e = np.exp(npa(w) / t)
    dist = e / np.sum(e)
    return dist

In [5]:
def softmax(w):
    w = numpy.array(w)

    maxes = numpy.amax(w, axis=1)
    maxes = maxes.reshape(maxes.shape[0], 1)
    e = numpy.exp(w - maxes)
    dist = e / numpy.sum(e, axis=1)

    return dist

In [ ]:
def softmax(w, t=1.0):
    """Calculate the softmax of a list of numbers w.

    Parameters
    ----------
    w : list of numbers
    t : float

    Return
    ------
    a list of the same length as w of non-negative numbers

    Examples
    --------
    >>> softmax([0.1, 0.2])
    array([ 0.47502081,  0.52497919])
    >>> softmax([-0.1, 0.2])
    array([ 0.42555748,  0.57444252])
    >>> softmax([0.9, -10])
    array([  9.99981542e-01,   1.84578933e-05])
    >>> softmax([0, 10])
    array([  4.53978687e-05,   9.99954602e-01])
    """
    e = numpy.exp(numpy.array(w) / t)
    dist = e / numpy.sum(e)
    return dist

In [ ]:
def softmax(w, t = 1.0):
    e = np.exp(npa(w) / t)
    dist = e / np.sum(e)
    return dist

def softmax_2(x):
    e_x = np.exp(x - np.max(x))
    out = e_x / e_x.sum()
    return out

In [6]:
def softmax(w, t = 1.0):
    e = np.exp(w, axes=0)
    dist = e / np.sum(e)
    return dict

In [ ]:
def softmax(w, t=1.0):
    e = np.exp(w)
    dist = e/np.sum(e, axis=0)
    return dist 