In [20]:
import numpy as np
from scipy import stats

In [21]:
# https://gist.github.com/stober/1946926

In [23]:
C = 3
X = np.array([[1.1, 2.3], [3.2, 4.1], [3.7, 4.2], [5.4, 6.8]])
N, D = X.shape
W = stats.norm.rvs(size = (D, C))
X.dot(W)

array([[ -3.77204727,  -1.03680234,  -1.77899752],
       [ -7.74013699,  -2.59767786,  -2.32640284],
       [ -8.27490916,  -2.9162452 ,  -2.09545311],
       [-12.91329781,  -4.36440132,  -3.79523193]])

In [43]:
def softmax(w):
    e = np.exp(w)
    return e / np.sum(e, axis = 0)

Z = softmax(X.dot(W).T).T
print np.sum(Z, axis = 1)
Z

[ 1.  1.  1.  1.]


array([[  4.21027874e-02,   6.48952079e-01,   3.08945134e-01],
       [  2.52140472e-03,   4.31503362e-01,   5.65975234e-01],
       [  1.43643028e-03,   3.05156579e-01,   6.93406991e-01],
       [  7.00250480e-05,   3.61403197e-01,   6.38526778e-01]])

In [36]:
def softmax(X, W):
    Z = []
    for x in X:
        Z.append([np.exp(W[:, c].dot(x)) / np.sum([np.exp(W[:, cc].dot(x)) for cc in range(C)]) for c in range(C)])
    return Z
    
Z = softmax(X, W)
print np.sum(Z, axis = 1)
Z

[ 1.  1.  1.  1.]


[[0.042102787383074401, 0.64895207858308879, 0.30894513403383672],
 [0.0025214047187365239, 0.43150336158289898, 0.56597523369836444],
 [0.0014364302764987549, 0.30515657884197323, 0.69340699088152802],
 [7.0025048000830789e-05, 0.36140319670693577, 0.63852677824506343]]