In [14]:
import numpy as np
from numpy.linalg import eigh, inv, svd
import htwt
from sklearn.preprocessing import scale

In [2]:
def summary(X):
    print np.mean(X)
    print np.cov(X, ddof = 0, rowvar = False)

In [3]:
X, y = htwt.get()
summary(X)

106.50952381
[[   19.78331066   104.01931973]
 [  104.01931973  1063.86340136]]


In [23]:
def whiten(X):
    cov = X.T.dot(X) # ???
    cov = np.cov(X, ddof = 0, rowvar = False)
    d, U = eigh(cov)
    D = np.diag(d)
    mean = np.mean(X, axis = 0)
    return (inv(D) ** 0.5).dot(U.T).dot((X - mean).T).T

summary(whiten(X))

1.33015291903e-15
[[  1.00000000e+00   2.63810138e-16]
 [  2.63810138e-16   1.00000000e+00]]


In [24]:
import scipy.cluster.vq

def whiten(X):
    return scipy.cluster.vq.whiten(X)

summary(whiten(scale(X)))

-4.54662762466e-16
[[ 1.          0.71700402]
 [ 0.71700402  1.        ]]


In [25]:
def whiten(X):
    U, s, Vt = svd(X)
    return U.dot(Vt)

summary(whiten(X))

ValueError: shapes (210,210) and (2,2) not aligned: 210 (dim 1) != 2 (dim 0)