In [1]:
import numpy as np
from numpy.linalg import eigh, inv, svd
import datasets
from sklearn.preprocessing import scale

In [ ]:
# ZCA ?

In [2]:
def summary(X):
    print np.mean(X)
    print np.cov(X, ddof = 0, rowvar = False)

In [3]:
X, y = datasets.htwt()
summary(X)

106.51
[[   19.78331066   104.01931973]
 [  104.01931973  1063.86340136]]


In [12]:
summary(scale(X)) # scale centers individual feature and scales variances to 1

-4.67755e-07
[[ 0.99999991  0.71700404]
 [ 0.71700404  1.00000016]]


In [15]:
def whiten(X, zca = False): #centers individual feature and scales / rotates covariance to I
    cov = X.T.dot(X) # ???
    cov = np.cov(X, ddof = 0, rowvar = False)
    d, U = eigh(cov)
    D = np.diag(d)
    mean = np.mean(X, axis = 0)
    X_new = (inv(D) ** 0.5).dot(U.T).dot((X - mean).T).T
    return U.dot(X_new) if zca else X_new

summary(whiten(X, zca = False))

2.80336482487e-07
[[  1.00000000e+00  -1.86094526e-16]
 [ -1.86094526e-16   1.00000000e+00]]


In [25]:
def whiten(X):
    U, s, Vt = svd(X)
    return U.dot(Vt)

summary(whiten(X))

ValueError: shapes (210,210) and (2,2) not aligned: 210 (dim 1) != 2 (dim 0)