In [10]:
import numpy as np
from numpy.linalg import eigh, inv, svd
import htwt

In [2]:
def summary(X):
    print np.mean(X)
    print np.cov(X, ddof = 0, rowvar = False)

In [3]:
X, y = htwt.get()
summary(X)

106.50952381
[[   19.78331066   104.01931973]
 [  104.01931973  1063.86340136]]


In [6]:
import scipy.cluster.vq

def whiten(X):
    return scipy.cluster.vq.whiten(X)

summary(whiten(X))

9.80526965251
[[ 1.          0.71700402]
 [ 0.71700402  1.        ]]


In [9]:
import scipy.cluster.vq

def whiten(X, fudge = 1E-18):
    cov = X.T.dot(X)
    d, U = eigh(cov)
    D = np.diag(1.0 / np.sqrt(d + fudge))
    return X.dot(U.dot(D).dot(U.T))

summary(whiten(X))

0.0479161289009
[[ 0.00323177 -0.00221853]
 [-0.00221853  0.00154528]]


In [11]:
import scipy.cluster.vq

def whiten(X):
    U, s, Vt = svd(X)
    return U.dot(Vt)

summary(whiten(X))

ValueError: shapes (210,210) and (2,2) not aligned: 210 (dim 1) != 2 (dim 0)

In [13]:
import scipy.cluster.vq

def whiten(X):
    cov = np.cov(X, ddof = 0, rowvar = False)
    d, U = eigh(cov)
    D = np.diag(d)
    mean = np.mean(X, axis = 0)
    return (inv(D) ** 0.5).dot(U.T).dot((X - mean).T).T

summary(whiten(X))

1.33015291903e-15
[[  1.00000000e+00   2.63810138e-16]
 [  2.63810138e-16   1.00000000e+00]]
